version: "3"

services:

  gateway:
    build: ./gateway
    ports: 
      - 80:80
    links:
      - "vote"
    restart: always
    networks:
      - front-tier

  vote:
    build: ./vote
    container_name: vote
    command: npm start
    volumes:
      - ./vote:/app
      - ./vote/node_modules:/app/node_modules
    restart: on-failure
    networks:
      - front-tier
      - back-tier

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: