version: "3"

services:
  vote:
    build: ./vote
    command: npm start
    volumes:
      - ./vote:/app
      - ./vote/node_modules:/app/node_modules
    restart: on-failure
    networks:
      - front-tier
      - back-tier
  gateway:
    build: ./gateway
    ports: 
      - "80:80"
    links:
      - "vote"
    restart: always
    networks:
      - front-tier

networks:
  front-tier:
  back-tier: