version: "3"

services:

  rabbitmq:
    image: rabbitmq:3.7.4
    container_name: rabbitmq
    networks:
      - rabbitmq-tier

  gateway:
    image: nginx
    volumes:
      - ./common/view:/var/www
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    links:
      - "vote"
      - "result"
      - "candidate"
    restart: always
    networks:
      - front-tier

  vote:
    build: ./vote
    container_name: vote
    command: npm start
    environment:
      - RABBITMQ_URI=amqp://rabbitmq
      - EXCHANGE_NAME=votesExchange
      - CANDIDATE_AMPQ_KEY=candidate
      - CANDIDATE_VOTE_AMPQ_KEY=candidate_vote
      - VOTE_AMPQ_KEY=vote
    volumes:
      - ./vote:/app
      - ./vote/node_modules:/app/node_modules
      - ./tsconfig-base.json:/tsconfig-base.json
      - ./common:/common
    restart: on-failure
    networks:
      - front-tier
      - rabbitmq-tier
    depends_on:
      - rabbitmq

  worker:
    build: ./worker
    container_name: worker
    environment:
      - RABBITMQ_URI=amqp://rabbitmq
      - EXCHANGE_NAME=votesExchange
      - VOTE_AMPQ_KEY=vote
      - DB_URI=mysql://root:root@db:3306/voting_dev_db
    volumes:
      - ./worker:/app
      - ./worker/node_modules:/app/node_modules
      - ./tsconfig-base.json:/tsconfig-base.json
      - ./common:/common
    restart: on-failure
    networks:
      - rabbitmq-tier
      - db-tier
    depends_on:
      - rabbitmq
      - db

  result:
    build: ./result
    container_name: result
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
      - DB_URI=mysql://root:root@db:3306/voting_dev_db
    volumes:
      - ./result:/app
      - ./result/node_modules:/app/node_modules
      - ./tsconfig-base.json:/tsconfig-base.json
      - ./common:/common
    restart: on-failure
    networks:
      - front-tier
      - rabbitmq-tier
    depends_on:
      - rabbitmq
      - db

  candidate:
    build: ./candidate
    container_name: candidate
    environment:
      - RABBITMQ_URI=amqp://rabbitmq
      - EXCHANGE_NAME=votesExchange
      - CANDIDATE_AMPQ_KEY=candidate
      - DB_URI=mongodb://mongo:27017/candidate
    volumes:
      - ./candidate:/app
      - ./candidate/node_modules:/app/node_modules
      - ./tsconfig-base.json:/tsconfig-base.json
      - ./common:/common
    restart: on-failure
    networks:
      - front-tier
      - rabbitmq-tier
      - mongo-tier
    depends_on:
      - rabbitmq
      - mongo

  db:
    build: ./db
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-tier

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks: 
      - mongo-tier

volumes:
  db-data:
  mongo-data:

networks:
  rabbitmq-tier:
  front-tier:
  mongo-tier:
  db-tier: