version: "3"

services:

  gateway:
    image: nginx
    volumes:
      - ./common/view:/var/www
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    links:
      - "vote"
      - "result"
      - "candidate"
    restart: always
    networks:
      - front-tier

  vote:
    build: ./vote
    container_name: vote
    command: npm start
    environment:
      - RHOST=redis
      - RLIST_NAME=votes
      - CANDIDATE_URI=http://candidate:3003
    volumes:
      - ./vote:/app
      - ./vote/node_modules:/app/node_modules
      - ./tsconfig-base.json:/tsconfig-base.json
      - ./common:/common
    restart: on-failure
    networks:
      - front-tier
      - back-tier
    depends_on:
      - redis

  worker:
    build: ./worker
    container_name: worker
    environment:
      - RHOST=redis
      - RLIST_NAME=votes
      - DB_URI=mysql://root:root@db:3306/voting_dev_db
    volumes:
      - ./worker:/app
      - ./worker/node_modules:/app/node_modules
      - ./tsconfig-base.json:/tsconfig-base.json
      - ./common:/common
    restart: on-failure
    networks:
      - back-tier
    depends_on:
      - redis
      - db

  result:
    build: ./result
    container_name: result
    environment:
      - DB_URI=mysql://root:root@db:3306/voting_dev_db
      - CANDIDATE_URI=http://candidate:3003
    volumes:
      - ./result:/app
      - ./result/node_modules:/app/node_modules
      - ./tsconfig-base.json:/tsconfig-base.json
      - ./common:/common
    restart: on-failure
    networks:
      - front-tier
      - back-tier
    depends_on:
      - db

  candidate:
    build: ./candidate
    container_name: candidate
    environment:
      - DB_URI=mongodb://mongo:27017/candidate
    volumes:
      - ./candidate:/app
      - ./candidate/node_modules:/app/node_modules
      - ./tsconfig-base.json:/tsconfig-base.json
      - ./common:/common
    restart: on-failure
    networks:
      - front-tier
      - back-tier
    depends_on:
      - mongo

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
    ports: ["6379"]
    networks:
      - back-tier

  db:
    build: ./db
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - back-tier

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - back-tier
    

volumes:
  redis-data:
  db-data:
  mongo-data:

networks:
  front-tier:
  back-tier: