-- MySQL Script generated by MySQL Workbench
-- Tue Jan 22 21:36:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema voting_dev_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema voting_dev_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voting_dev_db` DEFAULT CHARACTER SET utf8 ;
USE `voting_dev_db` ;

-- -----------------------------------------------------
-- Table `voting_dev_db`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_dev_db`.`vote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `candidate_id` VARCHAR(40) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
PACK_KEYS = Default;


-- -----------------------------------------------------
-- Table `voting_dev_db`.`candidate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_dev_db`.`candidate` (
  `id` CHAR(36) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `company` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voting_dev_db`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_dev_db`.`result` (
  `id` CHAR(36) NOT NULL,
  `candidate_id` VARCHAR(40) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
