-- MySQL Script generated by MySQL Workbench
-- Fri Dec 14 00:21:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema voting_dev_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema voting_dev_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voting_dev_db` DEFAULT CHARACTER SET utf8 ;
USE `voting_dev_db` ;

-- -----------------------------------------------------
-- Table `voting_dev_db`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voting_dev_db`.`vote` (
  `id` BINARY(16) NOT NULL,
  `candidate_id` VARCHAR(16) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `voting_dev_db`;

DELIMITER $$
USE `voting_dev_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `voting_dev_db`.`vote_BEFORE_INSERT` BEFORE INSERT ON `vote` FOR EACH ROW
BEGIN
	SET new.id = UUID_TO_BIN(UUID());
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
